language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
stages:
- test
- deploy-staging
- deploy-production
jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy-staging
    script: ignore
    deploy:
    - provider: heroku
      app: petify-backend-staging
      skip_cleanup: true
      api_key:
        secure: mfqJYuD3pe2277TTl48ksmnIiP3dm02CFGhZ0pkouJKFQG5Oct1aqaW/xBpSA5cB8t2Ll1g7SADP1IC3+eJsnw/sjPfnUlZodU8pNHzJ4DI1GLhIr1oKoDrUUt7cCMN6q7Wc4Tyfeqb65Dv4+Jd2vKYH5/mCrpyyXhPXuL5Jv/2gx50dIMYvmRxj7kBXQBwzs8uJvJUr+H6DEwPhJ0BmL642oU1AXjCGLjTr7w2znE6aDON9f9Xnbw9sTzxBZ8DrrLdAJqmSi67GDGmtIlyLxlGkhqGTgibh/nGY/OywqJEwWDYHyfE3BksCyLavfdEyoTkTGhROj36VuYIQnUzLtAQwJI20nGgg9prv1zV9wMoQgPCyusvbAhbE0lmm6vVVLArpuJjI9DaYURSMlDFVARUswSAreok4yWXjJP8vbTLXz+awN0I+AGPoaSUSgMx13uPWh4MN/Z6FHmLAnWHGf8R6UejHbVDbRf6S60W87di3u29dKK2tjt1pWqxjcb0TEto+SJb93X0K5Xw6SIr3JAwIrXDLE8mbbXBIckM9thMxkNXdakmhPqOv3Z1xFgYGfI9jDQ/uxNdSV83lea4CBELu7fs5SlDZHI7GLi4HxDmA0iZIdlKjDCtVyWULoaAcoqiFskbb6yIfXoH+tab5FcPUtyR0zzh+pooXFmypdMs=
      on:
        branch: development
        repo: tdp2-1c2019/petify-backend
  - stage: deploy-production
    script: ignore
    deploy:
    - provider: heroku
      app: petify-backend
      skip_cleanup: true
      api_key:
        secure: NXPm83PgkaxOHUK6g6ljsUebaWxCIxFExtTbGBiZqbn7e85aFChhyexKACVAlDSvvYCo+spO66GSpWilpCxrfxOLRWLHgn/23XcotOXO8JTFSbhOoDBriVTeA2Er+lzvg/cDAgJuJpqAa1tIOHE0n4gKsXZJuZUCoCrV67EdUiNMc67Lwn8FOw31vr0gv3xD2YvmNT+iZMIx1MGK/10xueiz9N+bRhgJtebL8TwVnAyNz4ppoZIvzqIiCOrCo/Z5XtUHBqW/U+L/3Mr4yGNdLuvft7QJcOLvZ10rDpVSZ5KCHFkIVAxxwPG6M0kaYBUiammMVweQOOtUpKLApfZQNMuYId8BipACFd7Rw4n3/5ptr+ZSAEDxjTEnnlk3W+YAAQQrh30gqf9d0N34xkwRoIPRajAimWOeoK4Dvy6RKBafcx02t40iSljeT9tYjdh5kcTFmpVnY6ODgCaaKNIjTraXN/FJmhKCHE4x90HbE+8NgontsfsmL1NK+bYMDMOJqKbgsxHC0b0eS7+KMWRpIQttd9qsZvFYalDb9ivi52QPKN8Km5fTDtZNeSFHRqV66D+SJDK3BOYYY7v5U3/WPOJpyzFbGgKTD6gqQcGgRNX3Ssg/dwCS4hw17Oc59g2HywlV2URZ4sjNfua26TDJjb2uRX55cXupCl3my4Vd0t4=
      on:
        branch: master
        repo: tdp2-1c2019/petify-backend
