language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
stages:
- test
- deploy-staging
- deploy-production
jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy-staging
    script: ignore
    deploy:
    - provider: heroku
      app: petify-backend-staging
      skip_cleanup: true
      api_key:
        secure: Wk/UAB0/5BUrDgjx4FMSG6028zQVmIGbk3ae+c4Wm7bLKQSoFL4r2HsiGptQ1tZqrgeBgJ+75msw1JVsMwMKLvEoJl5nR78ZD/GRu7Q6Ev9sq1vum3npJ1NCirS74u7kKaXO7780QZx3hdHqup6Bwj+2ouey6CkdZ/QZEHMrGFBkrpo2+8IyQiv02g90NSybmpvgqQ+TM0mDMSWGBNer0LyksRY6w7PGjS3VD4qvbOy+zzbW5bt26WPSgIzMv8+q/oIizlseDa8SrNV/0qLwqHkmrX8iRaBmx7qLX8hV4o0sy2V9iEVivZd2+FOk17WIoGvt2Nfu/qFZYQm5se1qp63utEewniAwUL6Gd0LIMqD3Lrklj7AQ9NIVougcZvhlwm98L4tqTZ1bwsS9LvqrpJk73bEM9DJSm7s4ZsjYBocIQR5gg/z9s0IeDey/UZPXniCNE7UwSQOqNKMFQpMrP6fa1OgG0PB48Zk/IRSuiIpb8srcWj5OmYJL8jHjJ4CwRYtEifuc5GCreZOJpq3Apvb2qXOpVCmbbJF6huQf7a6f8TsWgEEg6hHLoGnzTtfSGa/AtT1h8LWJ/DDRkaxAV3nQrJci58nQ/kBkZsLx+iIJ/QTrthAR6UMyM1UxdcxHXzrKOcthselqMUW4UkL7kFnuaTcInX2j4GbmWotsdtE=
      on:
        branch: development
        repo: tdp2-1c2019/petify-backend
  - stage: deploy-production
    script: ignore
    deploy:
    - provider: heroku
      app: petify-backend
      skip_cleanup: true
      api_key:
        secure: NXPm83PgkaxOHUK6g6ljsUebaWxCIxFExtTbGBiZqbn7e85aFChhyexKACVAlDSvvYCo+spO66GSpWilpCxrfxOLRWLHgn/23XcotOXO8JTFSbhOoDBriVTeA2Er+lzvg/cDAgJuJpqAa1tIOHE0n4gKsXZJuZUCoCrV67EdUiNMc67Lwn8FOw31vr0gv3xD2YvmNT+iZMIx1MGK/10xueiz9N+bRhgJtebL8TwVnAyNz4ppoZIvzqIiCOrCo/Z5XtUHBqW/U+L/3Mr4yGNdLuvft7QJcOLvZ10rDpVSZ5KCHFkIVAxxwPG6M0kaYBUiammMVweQOOtUpKLApfZQNMuYId8BipACFd7Rw4n3/5ptr+ZSAEDxjTEnnlk3W+YAAQQrh30gqf9d0N34xkwRoIPRajAimWOeoK4Dvy6RKBafcx02t40iSljeT9tYjdh5kcTFmpVnY6ODgCaaKNIjTraXN/FJmhKCHE4x90HbE+8NgontsfsmL1NK+bYMDMOJqKbgsxHC0b0eS7+KMWRpIQttd9qsZvFYalDb9ivi52QPKN8Km5fTDtZNeSFHRqV66D+SJDK3BOYYY7v5U3/WPOJpyzFbGgKTD6gqQcGgRNX3Ssg/dwCS4hw17Oc59g2HywlV2URZ4sjNfua26TDJjb2uRX55cXupCl3my4Vd0t4=
      on:
        branch: master
        repo: tdp2-1c2019/petify-backend
