language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
stages:
- test
- deploy-staging
- deploy-production
jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy-staging
    script: ignore
    deploy:
    - provider: heroku
      app: petify-backend-staging
      skip_cleanup: true
      api_key:
        secure: RnefBt4QsI6vtSGyAPefJYnApbfQVGCasVisjMIPfI/R8h5tqIHmm9RlxPnSanDSn0bpqxMr0+Y+bgJiPu8Z4DbVej5dhHo7ojyTAAo63P8fNwmutHq3Dc1OsqTJOuacYyQgV0kP6ncCA/vo4Tzrze3pNNrtZLjtznpvPcgoGw0Up6mu8hJZM+3UPS+18UMFXIlcMLeJwPGrU2TJ64K41jmyySObLsDHvQ/6wB0IPWBFECEHEhIjdTEnv8C1u1iJ6/n/sdjIcE8aZRlIoKRjgCdLicQxyxnvd/7Ng7BkxsaEAI+UAb4FdkHnuYgKtsW8HGPqhU9PPWHGDqn3lXabDQ1v4Ix1/1AI/rK3BxVs8FBwVW0kEl720pFh/B4Pg0Ngs3+qpmu9i8gK7RfHriLwNBuR7JOlFbHumImv1+rwJt2PaOoCzgaPFpPIL1nZR8xAg9QwI6Jrkc6pRZoTylbQVjBzkZyBmH/teOWCdDTsI6FpWNerlMua/6KVfCKopzix9HzpIE7m20xOie+GO/px3hFok4WEh3LAFZlF9q45sLGwnvswBZKoyMG+XOugULjwbiZPWsJdm8+wwmPaIONp2bHyTbTiCm/3iGwHKqX8+5/eJRfZam7/cH018W6xjZ75SZhtkLSPBHXVMUbJ5UrRgLxR+y9HZinzq0BI5efLc5M=
      on:
        branch: development
        repo: tdp2-1c2019/petify-backend
  - stage: deploy-production
    script: ignore
    deploy:
    - provider: heroku
      app: petify-backend
      skip_cleanup: true
      api_key:
        secure: NXPm83PgkaxOHUK6g6ljsUebaWxCIxFExtTbGBiZqbn7e85aFChhyexKACVAlDSvvYCo+spO66GSpWilpCxrfxOLRWLHgn/23XcotOXO8JTFSbhOoDBriVTeA2Er+lzvg/cDAgJuJpqAa1tIOHE0n4gKsXZJuZUCoCrV67EdUiNMc67Lwn8FOw31vr0gv3xD2YvmNT+iZMIx1MGK/10xueiz9N+bRhgJtebL8TwVnAyNz4ppoZIvzqIiCOrCo/Z5XtUHBqW/U+L/3Mr4yGNdLuvft7QJcOLvZ10rDpVSZ5KCHFkIVAxxwPG6M0kaYBUiammMVweQOOtUpKLApfZQNMuYId8BipACFd7Rw4n3/5ptr+ZSAEDxjTEnnlk3W+YAAQQrh30gqf9d0N34xkwRoIPRajAimWOeoK4Dvy6RKBafcx02t40iSljeT9tYjdh5kcTFmpVnY6ODgCaaKNIjTraXN/FJmhKCHE4x90HbE+8NgontsfsmL1NK+bYMDMOJqKbgsxHC0b0eS7+KMWRpIQttd9qsZvFYalDb9ivi52QPKN8Km5fTDtZNeSFHRqV66D+SJDK3BOYYY7v5U3/WPOJpyzFbGgKTD6gqQcGgRNX3Ssg/dwCS4hw17Oc59g2HywlV2URZ4sjNfua26TDJjb2uRX55cXupCl3my4Vd0t4=
      on:
        branch: master
        repo: tdp2-1c2019/petrify-backend
